### ISSUE TITLE
add ICS feed for events

### ISSUE THREAD

**Issue by dhellmann** [pyatl/big-peach#13]
As a PyATL member, I want to subscribe to a feed so my calendar automatically updates with details of upcoming events.

**Comment by dhellmann** [comment]
look at https://django-ical.readthedocs.io/en/latest/

**Comment by pryelluw** [comment]
We have some related code: 

https://github.com/pyatl/big-peach/blob/master/events/models.py#L59

**Comment by dhellmann** [comment]
Nice, that should make setting up a feed easier.
